language: d
script: ./travis.sh
sudo: false

matrix:
  include:
    - d: dmd-2.066.1
      env:
        - COVERAGE=true
          # set the GH_TOKEN to deploy documentation
        - secure: ZLjNzBaBmU7w1iAZ8D2YRmvNcGjmmCB45If0jujU1jyIW2JFJRSXaGrFBiPqSIJf67kyRXZt6dWFwBGDq9reMj7pCiSvY2UfCyH8IAZSUF90L3pSNCn2gh0al+ZZYs/qKx4JqSbFGgFrnycb2OczRToF3Gj6nCKRZKA6tSzmCdU=
    - d: dmd-2.067.0-rc1
    - d: gdc-4.9.0
    - d: ldc-0.15.1
