language: d
script: ./travis.sh
sudo: false

matrix:
  include:
    - d: dmd
      env:
        - COVERAGE=true
          # set the GH_TOKEN to deploy documentation
        - secure: hlFUuPx9WMLTaW3qLGQJ/5W6tEjutllkeeAQz9S0wfXU8wtyUY+zcLsszlY8fTL5DqaBRPAuyrP5wvLfC5iO3FcABYasAT5O0l8drwznOjJdHguDrcKXORy9zsvNXV4ozUBiI2/YUC6MXVFW03tr0oDPGBLLqn7LNFK8NkO5URY=
      addons:
        apt:
          packages:
          - libevent-dev
          - libssl-dev
          - pkg-config
          - zlib1g-dev
    - d: dmd
      os: osx
    - d: gdc
    - d: ldc

cache:
  directories:
  - $HOME/.dub
