language: d

#compiler:
#  - ldc2

install:
  # ldc2
  # dub
  - LDC2_VERSION=0.12.1
  - DUB_VERSION=0.9.20
  - OS=linux
  - ARCH=x86_64
  - LDC2=ldc2-${LDC2_VERSION}-${OS}-${ARCH}
  - DUB=dub-${DUB_VERSION}-${OS}-${ARCH}
  - wget https://github.com/ldc-developers/ldc/releases/download/v${LDC2_VERSION}/${LDC2}.tar.xz
  - tar -Jxf ${LDC2}.tar.xz
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - tar -zxf ${DUB}.tar.gz

script:
  - ./dub --config=unittest --build=unittest --compiler=./${LDC2}/bin/ldmd2

branches:
  only:
    - master

notifications:
  email: true
