// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'bloom', kind: "module", path: './bloom.html', attributes: []},
{name: 'bloom.BloomFilter', kind: "structdeclaration", path: './bloom/BloomFilter.html', attributes: []},
{name: 'bloom.BloomFilter.clear', kind: "functiondeclaration", path: './bloom/BloomFilter.clear.html', attributes: []},
{name: 'bloom.BloomFilter.insert', kind: "functiondeclaration", path: './bloom/BloomFilter.insert.html', attributes: []},
{name: 'bloom.BloomFilter.reset', kind: "functiondeclaration", path: './bloom/BloomFilter.reset.html', attributes: []},
{name: 'bloom.BloomFilter.resize', kind: "functiondeclaration", path: './bloom/BloomFilter.resize.html', attributes: []},
{name: 'bloom.BloomFilter.size', kind: "functiondeclaration", path: './bloom/BloomFilter.size.html', attributes: ["const"]},
{name: 'bloom.BloomFilter.test', kind: "functiondeclaration", path: './bloom/BloomFilter.test.html', attributes: ["const"]},
{name: 'bloom.BloomFilter.this', kind: "functiondeclaration", path: './bloom/BloomFilter.this.html', attributes: []},
{name: 'bloom.CheapHash', kind: "aliasdeclaration", path: './bloom/CheapHash.html', attributes: []},
];
